apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inboxfewer.fullname" . }}
  labels:
    {{- include "inboxfewer.labels" . | nindent 4 }}
data:
  transport: {{ .Values.config.transport | quote }}
  http-addr: {{ .Values.config.httpAddr | quote }}
  yolo: {{ .Values.config.yolo | quote }}
  debug: {{ .Values.config.debug | quote }}
  disable-streaming: {{ .Values.config.disableStreaming | quote }}


