{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "inboxfewer.fullname" . }}
  labels:
    {{- include "inboxfewer.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "inboxfewer.selectorLabels" . | nindent 6 }}
  policyTypes:
  {{- range .Values.networkPolicy.policyTypes }}
  - {{ . }}
  {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
  {{- toYaml .Values.networkPolicy.ingress | nindent 2 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
  {{- toYaml .Values.networkPolicy.egress | nindent 2 }}
  {{- end }}
{{- end }}


