{{- if not .Values.existingSecret }}
{{- if or .Values.google.clientId .Values.google.clientSecret .Values.oauthSecurity.encryptionKey .Values.oauthSecurity.registrationAccessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inboxfewer.fullname" . }}
  labels:
    {{- include "inboxfewer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.google.clientId }}
  google-client-id: {{ .Values.google.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.google.clientSecret }}
  google-client-secret: {{ .Values.google.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauthSecurity.encryptionKey }}
  oauth-encryption-key: {{ .Values.oauthSecurity.encryptionKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauthSecurity.registrationAccessToken }}
  oauth-registration-token: {{ .Values.oauthSecurity.registrationAccessToken | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}


